django/src/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    # Top
    path('', views.TopPage.as_view(), name='top_page'),
    # Login, Logout
    path('login/', views.LoginPage.as_view(), name='login'),
    path('logout/', views.LogoutPage.as_view(), name='logout'),
    # account list
    path('accounts_page/', views.AccountsPage.as_view(), name='accounts_page'),
    # Edit account status
    path('update/<pk>/', views.UpdateUserStatus.as_view(), name='update_user_status'),
    path('delete/<pk>/', views.DeleteUserPage.as_view(), name='delete_user_page'),
    # Register user information
    path('create_user/', views.CreateUser.as_view(), name='create_user'),
    path('create_user/done/', views.CreateUserDone.as_view(), name='create_user_done'),
    path('create_user/complete/<token>/', views.CreateUserComplete.as_view(), name='create_user_complete'),
    # Update account information
    path('detail_account_info/<int:pk>/', views.DetailAccountInfo.as_view(), name='detail_account_info'),
    path('update_account_info/<int:pk>/', views.UpdateAccountInfo.as_view(), name='update_account_info'),
    path('delete_own_account/<int:pk>/', views.DeleteOwnAccount.as_view(), name='delete_own_account'),
    # Change password
    path('change_own_password/', views.ChangePassword.as_view(), name='change_own_password'),
    path('change_own_password/complete/', views.ChangePasswordComplete.as_view(), name='password_change_complete'),
    # Reset Password
    path('reset_password/', views.ResetPassword.as_view(), name='reset_password'),
    path('reset_password/done/', views.ResetPasswordDone.as_view(), name='reset_password_done'),
    path('reset_password/confirm/<uidb64>/<token>/', views.ResetPasswordConfirm.as_view(), name='reset_password_confirm'),
    path('reset_password/complete/', views.ResetPasswordComplete.as_view(), name='reset_password_complete'),
    # Change E-mail address
    path('change_email/', views.ChangeEmail.as_view(), name='change_email'),
    path('change_email/done/', views.ChangeEmailDone.as_view(), name='change_email_done'),
    path('change_email/complete/<param>/<token>/', views.ChangeEmailComplete.as_view(), name='change_email_complete'),
]

django/src/sns/urls.py
from django.urls import path
from . import views

app_name = 'sns'

urlpatterns = [
    # Time line
    path('', views.TimeLineView.as_view(), name='time_line'),
    # Delete tweet
    path('delete_tweet/<int:pk>', views.DeleteTweetView.as_view(), name='tweet_delete'),
    # Search follower
    path('follower/search', views.SearchFollowerView.as_view(), name='search_follower'),
    # Create relationship
    path('follower/create', views.CreateRelationshipView.as_view(), name='create_follower'),
    # Delete relationship
    path('follower/delete/<int:pk>', views.DeleteRelationshipView.as_view(), name='delete_follower'),
]

django/src/web_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls',  namespace='registration')),
    path('sns/', include('sns.urls', namespace='sns')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('storage/', include('storage.urls', namespace='storage')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('deep_learning/', include('deep_learning.urls', namespace='deep_learning')),
    path('smarthome/', include('smarthome.urls', namespace='smarthome')),
]

django/src/templates/base.html
<!doctype html>
<html lang="ja">
{% load static %}
<head>
    {# Required meta tags #}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {# Bootstrap CSS #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <style>
        .breadcrumb {
            background: transparent;
        }
    </style>
    <title>Web Service</title>
    {% block header %}
    {% endblock %}
</head>
{% load custom_filter %}
{% load django_bootstrap_breadcrumbs %}

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'registration:top_page' %}">Web Service</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-item nav-link" href="{% url 'registration:detail_account_info' user.pk %}">アカウント情報確認</a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="{% url 'registration:logout' %}">ログアウト</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'registration:login' %}">
                    ログイン
                    </a>
                </li>
            {% endif %}
            </ul>
        </div>
    </nav>
    {# main contents #}
    {% block breadcrumbs %}
        {% clear_breadcrumbs %}
        {% breadcrumb "Top" "/" %}
    {% endblock %}

    <div class="container mt-3">
        {% render_breadcrumbs %}
        {% block content %}{% endblock %}
    </div>
    {# Optional JavaScript #}
    {# jQuery first, then Bootstrap JS (Bundle version) #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
    <script src="{% static 'js/jquery.bootstrap-duallistbox.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-duallistbox.css' %}">
    {% block bodyjs %}
    {% endblock %}
</body>
</html>

django/src/templates/err_base.html
<!doctype html>
<html lang="ja">
{% load static %}
<head>
    {# Required meta tags #}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {# Bootstrap CSS #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <title>Web Service</title>
</head>
<body>
    {# main contents #}
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>
    {# Optional JavaScript #}
    {# jQuery first, then Popper.js, then Bootstrap JS #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
    <script src="{% static 'js/jquery.bootstrap-duallistbox.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-duallistbox.css' %}">
    <script>
        // redirect process
        (function(){
            setTimeout(() => {
                window.location.href = "{% url 'registration:top_page' %}";
            }, 3000);
        }());
    </script>
    </body>
</html>

django/src/templates/pagination.html
{% load pagination %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
    {# before #}
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{%  url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}

    {# number #}
    {% for num in paginator.page_range %}
        {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}
            {% if page_obj.number == num %}
            <li class="page-item active">
                <span class="page-link">
                    {{ num }}
                    <span class="sr-only">(current)</span>
                </span>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?{%  url_replace request 'page' num %}">
                    {{ num }}
                </a>
            </li>
            {% endif %}
        {% endif %}
    {% endfor %}

    {# next #}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?{%  url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>