django/src/sns/urls.py
from django.urls import path
from . import views

app_name = 'sns'

urlpatterns = [
    # Time line
    path('', views.TimeLineView.as_view(), name='time_line'),
    # Delete tweet
    path('delete_tweet/<int:pk>', views.DeleteTweetView.as_view(), name='tweet_delete'),
    # Search follower
    path('follower/search', views.SearchFollowerView.as_view(), name='search_follower'),
    # Create relationship
    path('follower/create', views.CreateRelationshipView.as_view(), name='create_follower'),
    # Delete relationship
    path('follower/delete/<int:pk>', views.DeleteRelationshipView.as_view(), name='delete_follower'),
]

django/src/web_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls',  namespace='registration')),
    path('sns/', include('sns.urls', namespace='sns')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('storage/', include('storage.urls', namespace='storage')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('deep_learning/', include('deep_learning.urls', namespace='deep_learning')),
    path('smarthome/', include('smarthome.urls', namespace='smarthome')),
]

django/src/sns/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MaxLengthValidator

User = get_user_model()

class Tweet(models.Model):
    # if reference user is deleted, related tweets also are deleted.
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # tweet text
    text = models.TextField(validators=[MinLengthValidator(1), MaxLengthValidator(140)])
    # create time
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        return self.text

class Relationship(models.Model):
    # follower relationship as seen by the user
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='relationship_owner')
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='relationship_follower')

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        return '{}-{}'.format(self.owner.username, self.follower.username)

django/src/sns/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.utils.translation import ugettext_lazy
from . import models

User = get_user_model()

class CreateTweetForm(forms.ModelForm):
    """
    Form of updating user status
    """
    class Meta:
        model = models.Tweet
        fields = ('text', )
        widgets = {
            'text': forms.Textarea(attrs={
                'rows': 4, 'cols': 15, 'style':'resize:none;'
            })
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class CreateRelationshipForm(forms.ModelForm):
    """
    Form of updating follower status
    """
    owner_id = forms.IntegerField()
    follower_id = forms.IntegerField()

    class Meta:
        model = models.Relationship
        exclude = ('owner', 'follower')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('request_user') if 'request_user' in kwargs else None
        super().__init__(*args, **kwargs)
        self.fields['owner_id'].widget = forms.HiddenInput()
        self.fields['follower_id'].widget = forms.HiddenInput()

    def clean_owner_id(self):
        owner_id = self.cleaned_data.get('owner_id')

        if self.user is None or owner_id != self.user.pk:
            raise forms.ValidationError(ugettext_lazy('Error: This POST request must be submitted by login user.'))

        return owner_id

    def clean_follower_id(self):
        follower_id = self.cleaned_data.get('follower_id')

        if self.user is None or follower_id == self.user.pk:
            raise forms.ValidationError(ugettext_lazy('Error: Login users cannot be registered as followers.'))

        return follower_id

    def save(self, commit=True):
        owner_id = self.cleaned_data.get('owner_id')
        follower_id = self.cleaned_data.get('follower_id')

        owner = User.objects.get(pk=owner_id)
        follower = User.objects.get(pk=follower_id)
        instance, _ = models.Relationship.objects.get_or_create(owner=owner, follower=follower)

        if commit:
            instance.save()

        return instance

django/src/sns/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, AccessMixin
from django.contrib.auth.models import Permission
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.http import Http404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django_filters.views import FilterView
from django.db.models import Q
from . import models, forms
from .filters import UserFilter

User = get_user_model()

class TimeLineView(LoginRequiredMixin, CreateView):
    """
    List tweet and create own tweet
    """
    template_name = 'sns/time_line.html'
    form_class = forms.CreateTweetForm
    success_url = reverse_lazy('sns:time_line')

    def get_context_data(self, **kwargs):
        user_pk = self.request.user.pk
        # filter the follow users
        follower_relationship = [element['follower_id'] for element in models.Relationship.objects.filter(owner__pk=user_pk).values()]
        # filter the followed users
        follow_relationship = [element['owner_id'] for element in models.Relationship.objects.filter(follower__pk=user_pk).values()]
        queryset = models.Tweet.objects.filter(Q(user__pk=user_pk) | Q(user__pk__in=follower_relationship) | Q(user__pk__in=follow_relationship))
        kwargs['tweets'] = queryset.order_by('-created')

        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super().form_valid(form)

class DeleteTweetView(AccessMixin, DeleteView):
    raise_exception = True
    model = models.Tweet
    success_url = reverse_lazy('sns:time_line')

    def get(self, request, *args, **kwargs):
        # ignore direct access
        return self.handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        try:
            tweet = self.model.objects.get(pk=kwargs['pk'])
        except Exception:
            raise Http404

        # if user is not authenticated or tweet is not request user's
        if not request.user.is_authenticated or request.user.pk != tweet.user.pk:
            return self.handle_no_permission()
        # checks pass let http method handlers process the request
        return super().dispatch(request, *args, **kwargs)

class SearchFollowerView(LoginRequiredMixin, FilterView):
    template_name = 'sns/search_follower.html'
    model = User
    filterset_class = UserFilter

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['relationship_form'] = forms.CreateRelationshipForm()
        context['relationships'] = models.Relationship.objects.all()

        return context

class CreateRelationshipView(LoginRequiredMixin, CreateView):
    model = models.Relationship
    form_class = forms.CreateRelationshipForm

    def get(self, request, *args, **kwargs):
        return redirect('sns:search_follower')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request_user'] = self.request.user

        return kwargs

    def form_valid(self, form):
        form.save()

        return redirect('sns:search_follower')

    def form_invalid(self, form):
        return redirect('sns:search_follower')

class DeleteRelationshipView(AccessMixin, DeleteView):
    raise_exception = True
    model = models.Relationship
    success_url = reverse_lazy('sns:search_follower')

    def get(self, request, *args, **kwargs):
        # ignore direct access
        return self.handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        try:
            relationship = self.model.objects.get(pk=kwargs['pk'])
        except Exception:
            raise Http404

        # if user is not authenticated or owner is not request user's
        if not request.user.is_authenticated or request.user.pk != relationship.owner.pk:
            return self.handle_no_permission()
        # checks pass let http method handlers process the request
        return super().dispatch(request, *args, **kwargs)

django/src/templates/sns/breadcrumbs_sns.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "SNS" "sns:time_line" %}
{% endblock %}

django/src/templates/sns/breadcrumbs_sns_search_follower.html
{% extends 'sns/breadcrumbs_sns.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Search Follower" "sns:search_follower" %}
{% endblock %}

django/src/templates/sns/search_follower.html
{% extends "sns/breadcrumbs_sns_search_follower.html" %}
{% load user_filter %}

{% block content %}
{% if user.is_authenticated  %}
<div class="row justify-content-center">
    <div class="col-12">
        <h2 class="h2">フォロワーの検索</h2>
        <form method="GET">
            <div class="row">
                <div class="col-4 col-sm-6 col-md-6 col-lg-8 col-xl-8">
                    {{ filter.form.name }}
                </div>
                <div class="col-4 col-sm-3 col-md-3 col-lg-2 col-xl-2">
                    <button type="submit" class="btn btn-primary btn-block">検索</button>
                </div>
                <div class="col-4 col-sm-3 col-md-3 col-lg-2 col-xl-2">
                    <a href="{% url 'sns:time_line' %}" class="btn btn-secondary btn-block">戻る</a>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row justify-content-center mt-3">
    <div class="col-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>見つかったフォロワー</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for target in filter.qs|ignored_userpk:user.pk %}
                <tr>
                    {% with relationships|filtered_follower:user.pk|filtered_owner:target.pk|get_first_element as followed_user %}
                    {% if target.viewname %}
                    <td>{{ target.viewname }} <font color="gray">@{{ target.username }}</font>{% if followed_user %}（フォローされています）{% endif %}</td>
                    {% else %}
                    <td>{{ target.username }}{% if followed_user %}（フォローされています）{% endif %}</td>
                    {% endif %}
                    {% endwith %}
                    {% with relationships|filtered_follower:target.pk|filtered_owner:user.pk|get_first_element as exact_relation %}
                    <td>
                        {% if exact_relation %}
                        <button type="button" class="btn btn-secondary btn-md btn-block un-follow-modal-button" data-deleteurl="{% url 'sns:delete_follower' exact_relation.pk %}">
                            フォロー解除
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-primary btn-md btn-block follow-modal-button" data-ownerid="{{ user.pk }}" data-followerid="{{ target.pk }}">
                            フォロー
                        </button>
                        {% endif %}
                    </td>
                    {% endwith %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
<div class="row justify-content-center">
    <div class="col-12">
        ログイン後にフォロワーを検索できます。
    </div>
</div>
{% endif %}

<div class="modal" tabindex="-1" role="dialog" id="follow-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">フォローの確認</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>フォローしますか？</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'sns:create_follower' %}" method="POST" id="follow-form">
                    {% csrf_token %}
                    {{ relationship_form }}
                    <button type="submit" class="btn btn-primary">フォロー</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="un-follow-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">フォロー解除の確認</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>本当にフォローを解除しますか？</p>
            </div>
            <div class="modal-footer">
                <form action="" method="POST" id="un-follow-form">
                    {% csrf_token %}
                    {{ relationship_form }}
                    <button type="submit" class="btn btn-danger">フォロー解除</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block bodyjs %}
<script>
(function() {
    /* Follow */
    const followForm = document.getElementById('follow-form');
    const followModalButtons = document.getElementsByClassName('follow-modal-button');

    for (const button of followModalButtons) {
        button.addEventListener('click', () => {
            for (const element of followForm) {
                if (element.name === 'follower_id') {
                    element.value = button.dataset.followerid;
                }
                if (element.name === 'owner_id') {
                    element.value = button.dataset.ownerid;
                }
            }

            $('#follow-modal').modal({
                backdrop: true,
                keyboard: true,
            });
        });
    }

    /* Un follow */
    const unFollowForm = document.getElementById('un-follow-form');
    const unFollowModalButtons = document.getElementsByClassName('un-follow-modal-button');

    for (const button of unFollowModalButtons) {
        button.addEventListener('click', () => {
            unFollowForm.action = button.dataset.deleteurl;

            $('#un-follow-modal').modal({
                backdrop: true,
                keyboard: true,
            });
        });
    }
}())
</script>
{% endblock %}

django/src/templates/sns/time_line.html
{% extends "sns/breadcrumbs_sns.html" %}
{% load humanize %}

{% block header %}
<style>
    ul {
        list-style: none;
    }
</style>
{% endblock %}

{% block content %}
{% if user.is_authenticated  %}
<div class="row justify-content-center">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form action="{% url 'sns:time_line' %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            {{ field }}
                        {% endfor %}
                        </div>
                    </div>
                    <div class="row mt-1">
                        <div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3">
                            <a href="{% url 'sns:search_follower' %}" class="btn btn-success btn-block" target="_self">フォロワーを探す</a>
                        </div>
                        <div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3 offset-lg-6 offset-xl-6">
                            <button type="submit" class="btn btn-primary btn-block">つぶやく</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center mt-3">
    <div class="col-12">
        {% for tweet in tweets %}
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-8 col-sm-8 col-md-8 col-lg-10 col-xl-10">
                    {% if tweet.user.viewname %}
                        <ul>
                            <li>{{ tweet.user.viewname }} <font color="gray">@{{ tweet.user.username }} {{ tweet.created|naturaltime }}</font></li>
                            <li>{{ tweet.text }}</li>
                        </ul>
                    {% else %}
                        <ul>
                            <li>{{ tweet.user.username }} {{ tweet.created|naturaltime }}</li>
                            <li>{{ tweet.text }}</li>
                        </ul>
                    {% endif %}
                    </div>
                    <div class="col-4 col-sm-4 col-md-4 col-lg-2 col-xl-2">
                        {% ifequal tweet.user.pk user.pk %}
                        <button type="button" class="btn btn-danger btn-block delete-modal-button" data-deleteurl="{% url 'sns:tweet_delete' tweet.pk %}">削除</button>
                        {% endifequal %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="row justify-content-center">
    <div class="col-12">
        ログイン後にツイートが表示されます。
    </div>
</div>
{% endif %}

<div class="modal" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">削除の確認</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>本当に削除してよろしいですか？</p>
                <p><font color="red">この操作はやり直せません</font></p>
            </div>
            <div class="modal-footer">
                <form action="" method="POST" id="delete-form">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">本当に削除</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block bodyjs %}
<script>
(function() {
    const deleteForm = document.getElementById('delete-form');
    const deleteModalButtons = document.getElementsByClassName('delete-modal-button');

    for (const button of deleteModalButtons) {
        button.addEventListener('click', () => {
            deleteForm.action = button.dataset.deleteurl;

            $('#modal').modal({
                backdrop: true,
                keyboard: true,
            });
        });
    }
}());
</script>
{% endblock %}