django/src/deep_learning/urls.py
from django.urls import path
from . import views

app_name = 'deep_learning'

urlpatterns = [
    # top page
    path('', views.TopPageView.as_view(), name='index'),
    # what_docker
    path('what_docker/', views.WhatDockerView.as_view(), name='what_docker'),
    # docker_environment
    path('docker_environment/', views.DockerEnvironmentView.as_view(), name='docker_environment'),
    # use_docker
    path('use_docker/', views.UseDockerView.as_view(), name='use_docker'),
    # jupyter_notebook
    path('jupyter_notebook/', views.JupyterNotebookView.as_view(), name='jupyter_notebook'),
    # tutorial_mnist_dataset
    path('tutorial_mnist_dataset/', views.TutorialMnistDatasetView.as_view(), name='tutorial_mnist_dataset'),
    # handwriting_recognition
    path('handwriting_recognition/', views.HandwritingRecognitionView.as_view(), name='handwriting_recognition'),
]

django/src/sns/urls.py
from django.urls import path
from . import views

app_name = 'sns'

urlpatterns = [
    # Time line
    path('', views.TimeLineView.as_view(), name='time_line'),
    # Delete tweet
    path('delete_tweet/<int:pk>', views.DeleteTweetView.as_view(), name='tweet_delete'),
    # Search follower
    path('follower/search', views.SearchFollowerView.as_view(), name='search_follower'),
    # Create relationship
    path('follower/create', views.CreateRelationshipView.as_view(), name='create_follower'),
    # Delete relationship
    path('follower/delete/<int:pk>', views.DeleteRelationshipView.as_view(), name='delete_follower'),
]

django/src/web_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls',  namespace='registration')),
    path('sns/', include('sns.urls', namespace='sns')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('storage/', include('storage.urls', namespace='storage')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('deep_learning/', include('deep_learning.urls', namespace='deep_learning')),
    path('smarthome/', include('smarthome.urls', namespace='smarthome')),
]

django/src/deep_learning/views.py
from django.views.generic import TemplateView

class TopPageView(TemplateView):
    template_name = 'deep_learning/index.html'

class WhatDockerView(TemplateView):
    template_name = 'deep_learning/what_docker.html'

class DockerEnvironmentView(TemplateView):
    template_name = 'deep_learning/docker_environment.html'

class UseDockerView(TemplateView):
    template_name = 'deep_learning/use_docker.html'

class JupyterNotebookView(TemplateView):
    template_name = 'deep_learning/jupyter_notebook.html'

class TutorialMnistDatasetView(TemplateView):
    template_name = 'deep_learning/tutorial_mnist_dataset.html'

class HandwritingRecognitionView(TemplateView):
    template_name = 'deep_learning/handwriting_recognition.html'

django/src/templates/deep_learning/breadcrumbs_deep_learning.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Deep Learing" "deep_learning:index" %}
{% endblock %}

{% block header %}
<style>
    .page-top {
        position: fixed;
        bottom: 20px;
        right: 20px;
        font-size: 77%;
        visibility: hidden;
    }
    .page-top a {
        background: #666;
        text-decoration: none;
        color: #fff;
        width: 100px;
        padding: 15px 0;
        text-align: center;
        display: block;
        border-radius: 5px;
    }
    .page-top a:hover {
        text-decoration: none;
        background: #999;
    }
</style>
{% endblock %}

{% block bodyjs %}
<script>
    $(function() {
        const topBtn = $('.page-top');
        topBtn.hide();
        topBtn.css('visibility', 'visible');
        $(window).scroll(function () {
            if ($(this).scrollTop() > 100) {
                topBtn.fadeIn();
            } else {
                topBtn.fadeOut();
            }
        });
        topBtn.click(function () {
            $('body,html').animate({
                scrollTop: 0
            }, 500);
            return false;
        });
    });
</script>
{% endblock %}

django/src/templates/deep_learning/breadcrumbs_deep_learning_mnist.html
{% extends 'deep_learning/breadcrumbs_deep_learning.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "MNISTのデータセットを用いた手書き文字認識" "deep_learning:tutorial_mnist_dataset" %}
{% endblock %}

django/src/templates/deep_learning/docker_environment.html
{% extends 'deep_learning/breadcrumbs_deep_learning.html' %}
{% load django_bootstrap_breadcrumbs %}
{% load static %}

{% block header %}
{{ block.super }}
{# code syntax #}
<link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/dracula.min.css">
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Docker環境構築" "deep_learning:docker_environment" %}
{% endblock %}

{% block content %}
<div class="row justify-content-center mt-1">
    <div class="col-12">
        <div class="row mt-2">
            <div class="col-12">
                <h1 class="h1 mt-2">深層学習入門</h1>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 class="h4 mt-2 border-bottom">目次</h4>
                <ul>
                    <li class="tableofcontents_list">
                        <a href="#for_windows7" target="_self">Docker環境構築（Window7編）</a>
                    </li>
                    <li class="tableofcontents_list">
                        <a href="#for_windows10" target="_self">Docker環境構築（Window10編）</a>
                    </li>
                    <li class="tableofcontents_list">
                        <a href="#for_Ubuntu" target="_self">Docker環境構築（Ubuntu編）</a>
                    </li>
                    <li class="tableofcontents_list">
                        <a href="#for_Mac" target="_self">Docker環境構築（Mac編）</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 id="for_windows7" class="h4 mt-2 border-bottom">Docker環境構築（Window7編）</h4>
                <p>
                    Widows7では、Windows上にDocker環境を構築できない。
                    このため、仮想マシンでLinux環境を構築しLinux環境でDockerを動かすこととなる。
                </p>
                <p>
                    ここでは、Windows環境にVirtual Boxをインストールし、仮想マシンにUbuntu環境を構築する。
                    Ubuntu環境でのDocker環境構築は「Docker環境構築（Ubuntu編）」を参照のこと。
                </p>

                <!-- Virtual Boxのダウンロード・インストール -->
                <h5 class="h5 mt-2 border-bottom">１．Virtual Boxのダウンロード・インストール</h5>
                <p>64bit版Windowsを利用している場合、<a href="https://www.virtualbox.org/wiki/Downloads" target="_blank">Download
                        VirtualBox</a>に移動し、VirtualBox 6.0.0 platform packagesの<span style="color: #f00;">「Windows
                        hosts」</span>をダウンロードする。（2018/01/12現在の最新版）</p>
                <div class="fullscreen-image"
                    data-image="{% static 'deeplearning_img/docker_environment/VirtualBox_win64bit.png' %}"
                    data-title="64bit版Windows" data-caption="64bit版Windows VirtualBox">
                    <img class="img-fluid" src="{% static 'deeplearning_img/docker_environment/VirtualBox_win64bit.png' %}"
                        alt="64bit版Windows VirtualBox Download">
                </div>
                <p>32bit版Windowsを利用している場合、<a href="https://www.virtualbox.org/wiki/Download_Old_Builds_5_2"
                        target="_blank">Download VirtualBox (Old Builds): VirtualBox 5.2</a>に移動し、VirtualBox 5.2.22
                    (released November 09 2018)の<span style="color: #f00;">「Windows
                        hosts」</span>をダウンロードする。（2018/01/12現在の最新版）</p>
                <div class="fullscreen-image"
                    data-image="{% static 'deeplearning_img/docker_environment/VirtualBox_win32bit.png' %}"
                    data-title="32bit版Windows" data-caption="32bit版Windows VirtualBox">
                    <img class="img-fluid" src="{% static 'deeplearning_img/docker_environment/VirtualBox_win32bit.png' %}"
                        alt="32bit版Windows VirtualBox Download">
                </div>
                <p>ダウンロード完了後、<a href="https://www.virtualbox.org/manual/ch02.html#installation_windows"
                        target="_blank">公式のマニュアル</a>を参考にインストールする。</p>

                <!-- Ubuntu環境の構築 -->
                <h5 class="h5 mt-2 border-bottom">２．Ubuntu環境の構築</h5>
                <p>ここでは、仮想ハードディスクイメージを利用してUbuntu環境を構築する。</p>
                <p><a href="https://www.ubuntulinux.jp/download/ja-remix-vhd"
                        target="_blank">仮想ハードディスクイメージのダウンロード</a>に移動し、<span
                        style="color: #f00;">「ubuntu-ja-14.04-desktop-amd64-vhd.zip」</span>をダウンロードする。</p>
                <div class="fullscreen-image"
                    data-image="{% static 'deeplearning_img/docker_environment/ubuntuHardDiskImage.png' %}"
                    data-title="仮想ハードディスクイメージ" data-caption="仮想ハードディスクイメージのページ">
                    <img class="img-fluid" src="{% static 'deeplearning_img/docker_environment/ubuntuHardDiskImage.png' %}"
                        alt="仮想ハードディスクイメージ">
                </div>
                <p>「仮想ハードディスクイメージのダウンロード」ページにある<span style="color: #f00;">「VirtualBoxでの利用方法」</span>を参考に環境を構築する。</p>
                <p>環境構築後、<a href="#for_Ubuntu" target="_self">Docker環境構築（Ubuntu編）</a>の内容を実施する。</p>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 id="for_windows10" class="h4 mt-2 border-bottom">Docker環境構築（Window10編）</h4>
                <h5 class="h5" style="color: #f00">Windows10（32bit版）を利用している人や下記の方法で動作しない人は、<a href="#for_windows7"
                        target="_self">Docker環境構築（Window7編）</a>の内容を実施すること。</h5>
                <p>
                    Windows10（64bit版）のEditionによりインストール方法が異なる。
                    また、筆者はWindows10の環境を用意できないため、外部サイトで公開されている方法を展開する。
                </p>

                <!-- Windows10 Home 64bit向け -->
                <h5 class="h5 mt-2 border-bottom">■ Windows10 Home 64bitを利用している人・Windows10
                    ProでHyper-Vに対応していないCPUを利用している人</h5>
                <p>
                    Windows10 Home 64bitを利用している人（殆どの人が該当する）やWindows10 ProでHyper-Vに対応していないCPUを利用している人は、「Docker
                    Toolbox」を利用する。
                    下記のサイトの<span style="color: #f00;">「ダウンロード」、「インストール」、「ファイル共有」</span>を実施する。<br>
                    <a href="https://qiita.com/idani/items/fb7681d79eeb48c05144" target="_blank">windows 10 home で
                        docker を導入するメモ</a>
                </p>

                <!-- Windows10 Pro 64bit向け -->
                <h5 class="h5 mt-2 border-bottom">■ Windows10 Pro 64bitを利用している人</h5>
                <p>
                    Windows10 Proを利用している人は、Windows自身が持つHyper-V機能を有効にすることで、
                    Docker for Windowsをインストール可能となる。
                    下記のサイトの<span style="color: #f00;">「Hyper-Vの有効化」、「Docker Community Edition for
                        Windowsのインストール」、「インストール確認」</span>を実施する。<br>
                    <a href="https://dev.classmethod.jp/cloud/aws/win10_docker_python_ecs_cfn/" target="_blank">Windows
                        10 にDockerをいれてPythonを実行して、その勢いでCloudFormation一発でECS上でも実行してみた</a>
                </p>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 id="for_Ubuntu" class="h4 mt-2 border-bottom">Docker環境構築（Ubuntu編）</h4>

                <div class="row">
                    <div class="col-9">
                        下記のShell Scriptを<span style="color: #f00;">installer.sh</span>で保存する。
                    </div>
                    <div class="col-3">
                        <button class="clip btn btn-primary btn-block" data-clipboard-target="#installer-shell-script">copy</button>
                    </div>
                </div>
                <pre class="mt-1"><code id="installer-shell-script">#!/bin/bash
if [ $# -lt 1 ]; then
    echo Usage: $0 "user_name"
    echo "ex)" $0 user
    exit 1
fi
user_name="$1"

# =============
# system update
# =============
echo updating...
sudo apt-get -y update &gt; /dev/null 2&gt;&amp;1
sudo apt-get -y upgrade
# install git
sudo apt-get install -y git

# ==========
# set up git
# ==========
{
    echo    "[user]"
    echo -e "\temail = ${user_name}@localhost"
    echo -e "\tname = ${user_name}"
    echo    "[alias]"
    echo -e "\ttree = log --graph --all --format=\"%x09%C(cyan bold)%an%Creset %C(yellow)%h%Creset %C(magenta reverse)%d%Creset %s\""
    echo    "[push]"
    echo -e "\tdefault = simple"
    echo    "[color]"
    echo -e "\tui = auto"
    echo    "[merge]"
    echo -e "\tff = false"
    echo    "[pull]"
    echo -e "\tff = only"
} &gt; /home/${user_name}/.gitconfig
sudo chown ${user_name}:${user_name} /home/${user_name}/.gitconfig

# =========================
# install required packages
# =========================
sudo apt-get install -y apt-transport-https ca-certificates software-properties-common
[ $(which curl) ] || sudo apt-get install -y curl
# get GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
# add docker repository
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
# =================
# install docker-ce
# =================
echo updating...
sudo apt-get -y update &gt; /dev/null 2&gt;&amp;1
sudo apt-get install -y --force-yes docker-ce
# check Version
sudo docker version
# ======================
# install docker-compose
# ======================
curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-$(uname -s)-$(uname -m) -o ~/docker-compose
sudo mv ~/docker-compose /usr/local/bin/
sudo chmod +x /usr/local/bin/docker-compose
sudo docker-compose --version

# ==================
# add user to docker
# ==================
if [ $(which docker) ]; then
    if [ $(cat /etc/group | grep docker | wc -l) -eq 0 ]; then
        # add group
        sudo groupadd  docker
    fi
    # add user
    sudo gpasswd -a ${user_name} docker
fi</code></pre>
                <p>
                    installer.shがあるディレクトリで、下記のコマンドを実行し、Docker環境を構築する。
                </p>
                <p>
                    この時、<span style="color: #f00;">パスワードを求められる</span>のでパスワードを入力する。
                    インストール完了後、installer.shを削除する。
                </p>
                <pre><code>sudo bash installer.sh ${USER}</code></pre>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 id="for_Mac" class="h4 mt-2 border-bottom">Docker環境構築（Mac OS編）</h4>
                <p>
                    下記のサイトの<span style="color: #f00;">「Docker for Macをインストール」</span>を実施し、Docker環境を構築する。<br>
                    <a href="https://qiita.com/kurkuru/items/127fa99ef5b2f0288b81" target="_blank">DockerをMacにインストールする
                        (更新：2018/5/14)</a>
                </p>
            </div>
        </div>
        <p class="page-top"><a href="#wrap">TOPに戻る</a></p>
    </div>
</div>

{# toastの処理 #}
<div class="position-fixed p-3" style="z-index: 5; right: 0; top: 0;">
    <div id="toast-success" class="toast hide" role="status" aria-live="assertive" aria-atomic="true" data-delay="1000">
        <div class="toast-header bg-info text-white">
            <strong class="mr-auto">ClipboardJS</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body bg-info text-white">
            クリップボードにコピーしました
        </div>
    </div>
</div>
<div class="position-fixed p-3" style="z-index: 5; right: 0; top: 0;">
    <div id="toast-failed" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true" data-delay="1000">
        <div class="toast-header bg-danger text-white">
            <strong class="mr-auto">ClipboardJS</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body bg-danger text-white">
            クリップボードへのコピーに失敗しました
        </div>
    </div>
</div>
{% endblock %}

{% block bodyjs %}
{{ block.super }}
<script src="https://unpkg.com/clipboard@2/dist/clipboard.min.js"></script>
<script>
(function() {
    let clipboard = new ClipboardJS('.clip');
    // 成功時の処理
    clipboard.on('success', (e) => {
        $('#toast-success').toast('show');
        // テキスト選択状態を解除
        e.clearSelection();
    });
    // エラー時の処理
    clipboard.on('error', (e) => {
        $('#toast-failed').toast('show');
    });
}());
</script>
{% endblock %}

django/src/templates/deep_learning/index.html
{% extends 'deep_learning/breadcrumbs_deep_learning.html' %}

{% block content %}
<div class="row justify-content-center mt-1">
    <div class="col-12">
        <div class="row mt-2">
            <div class="col-12">
                <h2 class="h2 mt-2">深層学習入門</h2>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <table class="table table-bordered table-hover">
                    <caption>ページ一覧</caption>
                    <thead>
                        <tr>
                            <th class="align-middle" scope="col">リンク</th>
                            <th class="align-middle" scope="col">対象ページの概要</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="align-middle" scope="row">
                                <a href="{% url 'deep_learning:what_docker' %}" class="btn btn-link btn-md btn-block">Dockerとは</a>
                            </td>
                            <td class="align-middle">
                                仮想マシンとDockerを比較し、Dockerのメリット・デメリットを理解する。
                            </td>
                        </tr>
                        <tr>
                            <td class="align-middle" scope="row">
                                <a href="{% url 'deep_learning:docker_environment' %}" class="btn btn-link btn-md btn-block">Docker環境の構築</a>
                            </td>
                            <td class="align-middle">
                                Windows7、Windows10、Linux(Ubuntu)、Mac OSを対象に、Docker環境の構築方法を紹介する。
                            </td>
                        </tr>
                        <tr>
                            <td class="align-middle" scope="row">
                                <a href="{% url 'deep_learning:use_docker' %}" class="btn btn-link btn-md btn-block">Dockerコンテナの起動</a>
                            </td>
                            <td class="align-middle">
                                深層学習用のDockerイメージからコンテナを起動する方法について説明する。
                            </td>
                        </tr>
                        <tr>
                            <td class="align-middle" scope="row">
                                <a href="{% url 'deep_learning:jupyter_notebook' %}" class="btn btn-link btn-md btn-block">Jupyterの使い方</a>
                            </td>
                            <td class="align-middle">
                                Web上でPythonスクリプトを記述・実行できるJupyterの紹介と使い方について説明する。
                            </td>
                        </tr>
                        <tr>
                            <td class="align-middle" scope="row">
                                <a href="{% url 'deep_learning:tutorial_mnist_dataset' %}" class="btn btn-link btn-md btn-block">MNISTのデータセットを<br>用いた手書き文字認識</a>
                            </td>
                            <td class="align-middle">
                                MNISTのデータセットを用いて手書き文字認識を行う。<br>
                                この例題を通して機械学習フレームワークの使い方を学ぶ。
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django/src/templates/deep_learning/use_docker.html
{% extends 'deep_learning/breadcrumbs_deep_learning.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block header %}
{{ block.super }}
{# code syntax #}
<link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/dracula.min.css">
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Dockerコンテナの起動" "deep_learning:use_docker" %}
{% endblock %}

{% block content %}
<div class="row justify-content-center mt-1">
    <div class="col-12">
        <div class="row mt-2">
            <div class="col-12">
                <h1 class="h1 mt-2">深層学習入門</h1>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 class="h4 mt-2 border-bottom">目次</h4>
                <ul>
                    <li class="tableofcontents_list">
                        <a href="#docker_image" target="_self">利用するDockerイメージの紹介</a>
                    </li>
                    <li class="tableofcontents_list">
                        <a href="#docker_container" target="_self">Dockerイメージからコンテナの作成・起動</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 id="docker_image" class="h4 mt-2 border-bottom">利用するDockerイメージの紹介</h4>
                <p>
                    Docker環境でアプリケーションを実行する際の方法は、下記に示す2通りある。
                </p>
                <ul>
                    <li>Docker Hubに公開されているDockerイメージを利用する。</li>
                    <li>Docker HubからベースとなるOSイメージだけを参照し、Dockerfileからイメージを作成する。</li>
                </ul>
                <p>
                    通常、Dockerイメージが存在しない場合、自分でDockerfileを記述しイメージを作成することとなる。<br>今回は、都合よく深層学習環境一式が揃ったイメージが存在したため、このイメージを利用する。
                </p>
                <p>
                    <a href="https://hub.docker.com/r/smizy/keras" target="_blank">docker-keras-tensorflow(Docker Hub)</a><br>
                    <a href="https://github.com/smizy/docker-keras-tensorflow" target="_blank">docker-keras-tensorflow(Git Hub)</a>
                </p>
                <p>
                    Dockerイメージは、コンテナの作成時に存在しなければ自動的にダウンロードされる。
                    このため、<span style="color: #f00;">Dockerイメージを自分でダウンロードする必要はない</span>。
                </p>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 id="docker_container" class="h4 mt-2 border-bottom">Dockerイメージからコンテナの作成・起動</h4>
                <!-- Windows10 Home 64bit向け -->
                <h5 class="h5 mt-2 border-bottom">■ Windows10 Home 64bitを利用している人・Windows10 ProでHyper-Vに対応していないCPUを利用している人</h5>
                <ol>
                    <li>「Docker Quickstart Terminal」を起動し、「bash」と入力する。</li>
                    <li>下記のコマンドを実行し、デスクトップに移動する。</li>
                    <pre><code>cd /c/Users/(Windowsのユーザ名)/Desktop</code></pre>
                    <li>下記のコマンドを実行し、作業ディレクトリに移動する。</li>
                    <pre><code>mkdir work
cd work</code></pre>
                    <li>下記のコマンドを実行し、コンテナを起動する。</li>
                    <pre><code>docker run -it --rm -v $(pwd):/work -w /work -p 8888:8888 smizy/keras:2.1-cpu-alpine</code></pre>
                    <li>コンテナ起動後、表示されるURLにアクセスする。</li>
                    <pre><code># 例
Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
    http://localhost:8888/?token=abcdefghijklmnopqrstuvwxyz0123456789abcdefghijkl</code></pre>
                </ol>

                <!-- Windows10 Pro 64bit向け -->
                <h5 class="h5 mt-2 border-bottom">■ Windows10 Pro 64bitを利用している人</h5>
                <ol>
                    <li>Windows10 Pro 64bitの人は、<span style="color: #f00;">管理者権限で</span>「Power Shell」を起動する。</li>
                    <li>下記のコマンドを実行し、デスクトップに移動する。</li>
                    <pre><code>Set-Location (Join-Path $Env:USERPROFILE Desktop);</code></pre>
                    <li>下記のコマンドを実行し、作業フォルダに移動する。</li>
                    <pre><code>New-Item work -ItemType Directory;
Set-Location work;</code></pre>
                    <li>下記のコマンドを実行し、コンテナを起動する。</li>
                    <pre><code>$cdir = "/$((Get-Location).Drive.Name.ToLowerInvariant())/$((Get-Location).Path.Replace('\', '/').Substring(3))";
docker run -it --rm -v "$cdir:/work" -w /work -p 8888:8888 smizy/keras:2.1-cpu-alpine;</code></pre>
                    <li>コンテナ起動後、表示されるURLにアクセスする。</li>
                    <pre><code># 例
Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
    http://localhost:8888/?token=abcdefghijklmnopqrstuvwxyz0123456789abcdefghijkl</code></pre>
                </ol>
                <!-- Linux or Mac向け -->
                <h5 class="h5 mt-2 border-bottom">■ Linux or Macを利用している人</h5>
                <ol>
                    <li>「Terminal」を起動後、下記のコマンドを実行し、作業ディレクトリに移動する。</li>
                    <pre><code>mkdir work
cd work</code></pre>
                    <li>下記のコマンドを実行し、コンテナを起動する。</li>
                    <pre><code>docker run -it --rm -v $(pwd):/work -w /work -p 8888:8888 smizy/keras:2.1-cpu-alpine</code></pre>
                    <li>コンテナ起動後、表示されるURLにアクセスする。</li>
                    <pre><code># 例
Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
    http://localhost:8888/?token=abcdefghijklmnopqrstuvwxyz0123456789abcdefghijkl</code></pre>
                </ol>
            </div>
        </div>
        <p class="page-top"><a href="#wrap">TOPに戻る</a></p>
    </div>
</div>
{% endblock %}

django/src/templates/deep_learning/what_docker.html
{% extends 'deep_learning/breadcrumbs_deep_learning.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Dockerとは" "deep_learning:what_docker" %}
{% endblock %}

{% block content %}
<div class="row justify-content-center mt-1">
    <div class="col-12">
        <div class="row mt-2">
            <div class="col-12">
                <h4 class="h4 mt-2 border-bottom">目次</h4>
                <ul>
                    <li class="tableofcontents_list">
                        <a href="#what_docker" target="_self">Dockerとは</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h4 id="what_docker" class="h4 mt-2 border-bottom">Dockerとは</h4>
                <p>Dockerについては下記のサイトを参考のこと。</p>
                <ul>
                    <li><a href="https://knowledge.sakura.ad.jp/13265/" target="_blank" class="btn btn-link btn-md">【外部サイト】Docker入門（第一回）～Dockerとは何か、何が良いのか～</a></li>
                    <li><a href="https://qiita.com/wMETAw/items/b9bc643ded4b92bf6add" target="_blank" class="btn btn-link btn-md">【外部サイト】Docker入門 #1 【Dockerとは】</a></li>
                </ul>
            </div>
        </div>
        <p class="page-top"><a href="#wrap">TOPに戻る</a></p>
    </div>
</div>
{% endblock %}