django/src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # top page
    path('', views.PostListView.as_view(), name='index'),
    # own post
    path('own/post/<int:pk>', views.OwnPostListView.as_view(), name='own_post'),
    ## own tag
    #path('own/tag/<int:pk>', views.OwnTagListView.as_view(), name='own_tag'),
    ## create, update or delete tag
    #path('tag/create', views.TagCreateView.as_view(), name='tag_create'),
    #path('tag/update/<int:pk>', views.TagUpdateView.as_view(), name='tag_update'),
    #path('tag/delete/<int:pk>', views.TagDeleteView.as_view(), name='tag_delete'),
    # create, update or delete post
    path('post/create', views.PostCreateView.as_view(), name='post_create'),
    path('post/update/<int:pk>', views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>', views.PostDeleteView.as_view(), name='post_delete'),
    # detail post
    path('post/detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    # create comment
    path('comment/create/<int:pk>', views.CommentCreateView.as_view(), name='comment_create'),
    # reply
    path('reply/create/<int:pk>', views.ReplyCreateView.as_view(), name='reply_create'),
    # file upload
    path('file/upload/', views.FileUploadView.as_view(), name='file_upload'),
]

django/src/sns/urls.py
from django.urls import path
from . import views

app_name = 'sns'

urlpatterns = [
    # Time line
    path('', views.TimeLineView.as_view(), name='time_line'),
    # Delete tweet
    path('delete_tweet/<int:pk>', views.DeleteTweetView.as_view(), name='tweet_delete'),
    # Search follower
    path('follower/search', views.SearchFollowerView.as_view(), name='search_follower'),
    # Create relationship
    path('follower/create', views.CreateRelationshipView.as_view(), name='create_follower'),
    # Delete relationship
    path('follower/delete/<int:pk>', views.DeleteRelationshipView.as_view(), name='delete_follower'),
]

django/src/web_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls',  namespace='registration')),
    path('sns/', include('sns.urls', namespace='sns')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('storage/', include('storage.urls', namespace='storage')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('deep_learning/', include('deep_learning.urls', namespace='deep_learning')),
    path('smarthome/', include('smarthome.urls', namespace='smarthome')),
]

django/src/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy

User = get_user_model()

class Tag(models.Model):
    """
    tag
    """
    # user
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # tag name
    name = models.CharField(ugettext_lazy('tag name'), max_length=255, unique=True)

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        return self.name

class Post(models.Model):
    """
    post
    """
    # user
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # title
    title = models.CharField(ugettext_lazy('title'), max_length=64)
    # body text
    text = models.TextField(ugettext_lazy('body text'))
    # tag information
    tags = models.ManyToManyField(Tag, verbose_name=ugettext_lazy('tag'), blank=True)
    # relation post
    relation_posts = models.ManyToManyField('self', verbose_name=ugettext_lazy('relation posts'), blank=True)
    # is public
    is_public = models.BooleanField(ugettext_lazy('public or private'), default=True)
    # description
    description = models.TextField(ugettext_lazy('description'), max_length=128)
    # keyword
    keywords = models.CharField(ugettext_lazy('post keyword'), max_length=255, default='')
    # create time
    created_at = models.DateTimeField(ugettext_lazy('create time'), default=timezone.now)
    # update time
    updated_at = models.DateTimeField(ugettext_lazy('update time'), default=timezone.now)

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        return self.title

class Comment(models.Model):
    """
    comment
    """
    # name
    name = models.CharField(ugettext_lazy('name'), max_length=255, default=ugettext_lazy('no name'))
    # comment text
    text = models.TextField(ugettext_lazy('comment'))
    # target post
    target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=ugettext_lazy('target post'))
    # create time
    created_at = models.DateTimeField(ugettext_lazy('create time'), default=timezone.now)

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        return self.text[:32]

class Reply(models.Model):
    """
    reply to comment
    """
    # name
    name = models.CharField(ugettext_lazy('name'), max_length=255, default=ugettext_lazy('no name'))
    # reply text
    text = models.TextField(ugettext_lazy('reply text'))
    # target comment
    target = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name=ugettext_lazy('target comment'))
    # create time
    created_at = models.DateTimeField(ugettext_lazy('create time'), default=timezone.now)

    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        return self.text[:20]

django/src/blog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, AccessMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import Http404, JsonResponse, HttpResponseBadRequest
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, FormView
from django.db.models import Q
from . import models, forms

User = get_user_model()

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        # Check primary key of user is equivalent or user is superuser
        chk_account = user.pk == self.kwargs['pk'] or user.is_superuser
        # Check permission
        chk_perm = user.has_perm('registration.view_user') and user.has_perm('auth.view_permission')
        ret = chk_account and chk_perm

        return ret

class PostListView(LoginRequiredMixin, ListView):
    """
    public blog list
    """
    model = models.Post
    template_name = 'blog/index.html'
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset().filter(Q(is_public=True) | Q(user=self.request.user))
        form = forms.PostSearchForm(self.request.GET or None)

        # check form
        if form.is_valid():
            queryset = form.filtered_queryset(queryset)
        # ordering
        queryset = queryset.order_by('-updated_at').prefetch_related('tags')

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['search_form'] = forms.PostSearchForm(self.request.GET or None)

        return context

class OwnPostListView(OnlyYouMixin, ListView):
    model = models.Post
    template_name = 'blog/own_post.html'
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset().filter(user=self.request.user)
        form = forms.PostSearchForm(self.request.GET or None)

        # check form
        if form.is_valid():
            queryset = form.filtered_queryset(queryset)
        # ordering
        queryset = queryset.order_by('-updated_at').prefetch_related('tags')

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['search_form'] = forms.PostSearchForm(self.request.GET or None, user=self.request.user)

        return context

class OwnTagListView(OnlyYouMixin, ListView):
    model = models.Tag
    template_name = 'blog/own_tag.html'
    paginate_by = 10
    context_object_name = 'tags'

    def get_queryset(self):
        queryset = super().get_queryset().filter(user=self.request.user)
        form = forms.TagSearchForm(self.request.GET or None)

        # check form
        if form.is_valid():
            queryset = form.filtered_queryset(queryset)
        # ordering
        queryset = queryset.order_by('-name')

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['search_form'] = forms.TagSearchForm(self.request.GET or None)

        return context

class TagCreateView(LoginRequiredMixin, CreateView):
    raise_exception = True
    model = models.Tag
    form_class = forms.TagForm
    template_name = 'blog/tag_create_form.html'
    success_url = reverse_lazy('blog:index')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()

        return super().form_valid(form)

class TagUpdateView(AccessMixin, UpdateView):
    raise_exception = True
    model = models.Tag
    form_class = forms.TagForm
    template_name = 'blog/tag_update_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs

    def dispatch(self, request, *args, **kwargs):
        try:
            tag = self.model.objects.get(pk=kwargs['pk'])
        except Exception:
            raise Http404

        # if user is not authenticated or tag is not request user's
        if not request.user.is_authenticated or request.user.pk != tag.user.pk:
            return self.handle_no_permission()
        # checks pass let http method handlers process the request
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('blog:own_tag', kwargs={'pk': self.request.user.pk})

class TagDeleteView(AccessMixin, DeleteView):
    raise_exception = True
    model = models.Tag

    def get(self, request, *args, **kwargs):
        # ignore direct access
        return self.handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        try:
            tag = self.model.objects.get(pk=kwargs['pk'])
        except Exception:
            raise Http404

        # if user is not authenticated or tag is not request user's
        if not request.user.is_authenticated or request.user.pk != tag.user.pk:
            return self.handle_no_permission()
        # checks pass let http method handlers process the request
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('blog:own_tag', kwargs={'pk': self.request.user.pk})

class PostCreateView(LoginRequiredMixin, CreateView):
    raise_exception = True
    model = models.Post
    form_class = forms.PostForm
    template_name = 'blog/post_create_form.html'
    success_url = reverse_lazy('blog:index')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()

        return super().form_valid(form)

class PostUpdateView(AccessMixin, UpdateView):
    raise_exception = True
    model = models.Post
    form_class = forms.PostForm
    template_name = 'blog/post_update_form.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['pk'] = self.kwargs['pk']

        return kwargs

    def dispatch(self, request, *args, **kwargs):
        try:
            post = self.model.objects.get(pk=kwargs['pk'])
        except Exception:
            raise Http404

        # if user is not authenticated or post is not request user's
        if not request.user.is_authenticated or request.user.pk != post.user.pk:
            return self.handle_no_permission()
        # checks pass let http method handlers process the request
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('blog:own_post', kwargs={'pk': self.request.user.pk})

class PostDeleteView(AccessMixin, DeleteView):
    raise_exception = True
    model = models.Post

    def get(self, request, *args, **kwargs):
        # ignore direct access
        return self.handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        try:
            post = self.model.objects.get(pk=kwargs['pk'])
        except Exception:
            raise Http404

        # if user is not authenticated or post is not request user's
        if not request.user.is_authenticated or request.user.pk != post.user.pk:
            return self.handle_no_permission()
        # checks pass let http method handlers process the request
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('blog:own_post', kwargs={'pk': self.request.user.pk})

class PostDetailView(LoginRequiredMixin, DetailView):
    raise_exception = True
    model = models.Post
    template_name = 'blog/post_detail.html'

    def get_object(self, queryset=None):
        try:
            post = super().get_object(queryset=queryset)
        except Exception:
            raise Http404

        if post.is_public or post.user.pk == self.request.user.pk:
            return post
        else:
            return self.handle_no_permission()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = forms.CommentForm()
        context['reply_form'] = forms.ReplyForm()

        return context

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = models.Comment
    form_class = forms.CommentForm

    def get(self, request, *args, **kwargs):
        return self.handle_no_permission()

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(models.Post, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()

        return redirect('blog:post_detail', pk=post_pk)

class ReplyCreateView(LoginRequiredMixin, CreateView):
    model = models.Reply
    form_class = forms.ReplyForm

    def get(self, request, *args, **kwargs):
        return self.handle_no_permission()

    def form_valid(self, form):
        comment = get_object_or_404(models.Comment, pk=self.kwargs['pk'])
        reply = form.save(commit=False)
        reply.target = comment
        reply.save()

        return redirect('blog:post_detail', pk=comment.target.pk)

class FileUploadView(LoginRequiredMixin, FormView):
    form_class = forms.FileUploadForm

    def get(self, request, *args, **kwargs):
        return self.handle_no_permission()

    def form_valid(self, form):
        path = form.save()
        scheme, hostname = self.request.scheme, self.request.get_host()
        url = '{}://{}{}'.format(scheme, hostname, path)

django/src/templates/blog/breadcrumbs_blog.html
{% extends 'base.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Blog" "blog:index" %}
{% endblock %}

django/src/templates/blog/own_post.html
{% extends 'blog/breadcrumbs_blog_own_post.html' %}
{% load static %}
{% load humanize %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/custom_checkbox.css' %}">
<script src="{% static 'js/blog_search_helper.js' %}"></script>
{% endblock %}

{% block content %}
{% if user.is_authenticated  %}
<div class="row justify-content-center">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">絞り込み検索</h5>
                <form action="", method="GET">
                    <div class="form-row">
                        <div class="col-12 col-sm-12 col-md-10 col-lg-10 col-xl-10">
                            <div class="row">
                                <div class="col-12">
                                    {{ search_form.search_word }}
                                </div>
                            </div>
                            <div class="row mt-1">
                                <div class="col-12">
                                    {{ search_form.tags }}
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2">
                            <div class="row">
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary btn-block">検索</button>
                                </div>
                            </div>
                            <div class="row mt-1">
                                <div class="col-12">
                                    <a href="{% url 'blog:own_post' user.pk %}" class="btn btn-secondary btn-block">全件表示</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center mt-3">
    <div class="col-12">
        <section>
        {% for post in posts %}
            {% if post.user.pk == user.pk %}
            <article>
                <div class="row">
                    <div class="col-8">
                        <h2 class="h2 mt-1"><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
                    </div>
                    <div class="col-4">
                        <div class="dropdown mt-2">
                            <a class="btn btn-outline-secondary btn-block dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                操作
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                <a href="{% url 'blog:post_update' post.pk %}" class="dropdown-item">編集</a>
                                <div class="dropdown-divider"></div>
                                <button type="button" class="dropdown-item delete-modal-button" data-deleteurl="{% url 'blog:post_delete' post.pk %}">
                                    <font color="red">削除</font>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <p>{{ post.description }}</p>
                        <div>
                            <time datetime="{{ post.updated_at|date:'Y-m-d' }}">{{ post.updated_at|naturaltime }}に更新</time>
                            {% for tag in post.tags.all %}
                            {% if tag.user.pk == user.pk %}
                            <span class="tag" data-pk="{{ tag.pk }}">{{ tag.name }}</span>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </article>
            {% endif %}
        {% empty %}
            <article>
                <p>表示できる記事がありません。</p>
            </article>
        {% endfor %}
        </section>
    </div>
</div>
{% if posts %}
<div class="row justify-content-center">
    <div class="col-12">
{% include "pagination.html" %}
    </div>
</div>
{% endif %}
{% else %}
<div class="row justify-content-center">
    <div class="col-12">
        ログイン後にブログ一覧が表示されます。
    </div>
</div>
{% endif %}

<div class="modal" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">削除の確認</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>本当に削除してよろしいですか？</p>
            </div>
            <div class="modal-footer">
                <form action="" method="POST" id="delete-form">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">本当に削除</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block bodyjs %}
<script>
(function() {
    const deleteForm = document.getElementById('delete-form');
    const deleteModalButtons = document.getElementsByClassName('delete-modal-button');

    for (const button of deleteModalButtons) {
        button.addEventListener('click', () => {
            deleteForm.action = button.dataset.deleteurl;

            $('#modal').modal({
                backdrop: true,
                keyboard: true,
            });
        });
    }
}());
</script>
{% endblock %}

django/src/templates/blog/post_detail.html
{% extends 'blog/breadcrumbs_blog.html' %}
{% load static %}
{% load humanize %}
{% load markdown_extras %}
{% load django_bootstrap_breadcrumbs %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/custom_checkbox.css' %}">
{# code syntax #}
<link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/styles/dracula.min.css">
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
{# MathJax #}
<script>
window.MathJax = {
  options: {
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process',
    renderActions: {
      find: [10, function (doc) {
        for (const node of document.querySelectorAll('script[type^="math/tex"]')) {
          const display = !!node.type.match(/; *mode=display/);
          const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
          const text = document.createTextNode('');
          const sibling = node.previousElementSibling;
          node.parentNode.replaceChild(text, node);
          math.start = {node: text, delim: '', n: 0};
          math.end = {node: text, delim: '', n: 0};
          doc.math.push(math);
          if (sibling && sibling.matches('.MathJax_Preview')) {
            sibling.parentNode.removeChild(sibling);
          }
        }
      }, '']
    }
  }
};
</script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb post.title "blog:post_detail" post.pk %}
{% endblock %}

{% block content %}
{% if user.is_authenticated  %}
<div class="row justify-content-center">
    <div class="col-12">
        <article>
        {% if post.is_public or post.user.pk == user.pk %}
            <section>
                <div class="row">
                    <div class="col-12">
                        <h1 class="h1">{{ post.title }}</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <time datetime="{{ post.updated_at|date:'Y-m-d' }}">{{ post.updated_at|naturaltime }}に更新</time>
                        {% for tag in post.tags.all %}
                        <span class="tag-no-click" data-pk="{{ tag.pk }}">{{ tag.name }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ post.text|markdown2html }}
                    </div>
                </div>
            </section>
            <section class="mt-5">
                <div class="row">
                    <div class="col-12">
                        <h3 class="h3">関連記事</h3>
                    </div>
                </div>
                {% for relation_post in post.relation_posts.all %}
                <div class="row">
                    <div class="col-12">
                        <h4 class="h4"><a href="{% url 'blog:post_detail' relation_post.pk %}">{{ relation_post.title }}</a></h4>
                        <p>{{ relation_post.description }}</p>
                        <div>
                            {% if relation_post.user.viewname %}
                            <span>{{ relation_post.user.viewname }} <font color="gray">@{{ relation_post.user.username }}</font> 作成</span>
                            {% else %}
                            <span>{{ relation_post.user.username }} 作成</span>
                            {% endif %}
                            <time datetime="{{ relation_post.updated_at|date:'Y-m-d' }}">（{{ relation_post.updated_at|naturaltime }}に更新）</time>
                            {% for tag in relation_post.tags.all %}
                            <span class="tag" data-pk="{{ tag.pk }}">{{ tag.name }}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="row">
                    <div class="col-12">
                        関連記事はありません。
                    </div>
                </div>
                {% endfor %}
            </section>
            <section class="mt-5">
                <div class="row">
                    <div class="col-6 col-md-6 col-lg-8 col-xl-8">
                        <h3 class="h3">コメント</h3>
                    </div>
                    <div class="col-6 col-md-6 col-lg-4 col-xl-4">
                        <button type="button" class="btn btn-outline-primary btn-block comment-modal-button">記事にコメントする</button>
                    </div>
                </div>
                {% for comment in post.comment_set.all %}
                <div class="row mb-3">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{ comment.name }} さん</h4>
                                <p>
                                    <time datetime="{{ comment.created_at|date:'Y-m-d' }}">{{ comment.created_at|naturaltime }}</time>
                                </p>
                                <div>
                                    {{ comment.text|markdown2html_with_escape }}
                                </div>
                                <p>
                                    <button type="button" class="btn btn-outline-primary reply-modal-button" data-replyurl="{% url 'blog:reply_create' comment.pk %}">
                                        返信する
                                    </button>
                                </p>

                                {% for reply in comment.reply_set.all %}
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="card-title">{{ reply.name }} さん</h4>
                                        <p>
                                            <time datetime="{{ reply.created_at|date:'Y-m-d' }}">{{ reply.created_at|naturaltime }}</time>
                                        </p>
                                        <div>
                                            {{ reply.text|markdown2html_with_escape }}
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="row">
                    <div class="col-12">
                        表示するコメントはありません。
                    </div>
                </div>
                {% endfor %}
            </section>
        {% else %}
            <p>記事を表示する権限がありません。</p>
        {% endif %}
        </article>
    </div>
</div>
{% else %}
<div class="row justify-content-center">
    <div class="col-12">
        ログイン後にブログの内容が表示されます。
    </div>
</div>
{% endif %}

<div class="modal" tabindex="-1" role="dialog" id="comment-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">コメントの作成</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>{{ post.title }}に対するコメント</p>
                <form action="{% url 'blog:comment_create' post.pk %}" method="POST" id="comment-form">
                    {% csrf_token %}
                    {{ comment_form }}
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" form="comment-form">コメントを送信する</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="reply-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">リプライの作成</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>コメントに対する返信</p>
                <form action="" method="POST" id="reply-form">
                    {% csrf_token %}
                    {{ reply_form }}
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" form="reply-form">リプライを送信する</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block bodyjs %}
<script>
(function() {
    $('.comment-modal-button').on('click', () => {
        $('#comment-modal').modal({
            backdrop: false,
            keyboard: true,
        });
    });

    const replyForm = document.getElementById('reply-form');
    const replyModalButtons = document.getElementsByClassName('reply-modal-button');

    for (const button of replyModalButtons) {
        button.addEventListener('click', () => {
            replyForm.action = button.dataset.replyurl;

            $('#reply-modal').modal({
                backdrop: false,
                keyboard: true,
            });
        });
    }
}());
</script>
{% endblock %}